### ISSUE TITLE
vec128.h issues

### ISSUE THREAD

**Issue by franziskuskiefer** [project-everest/hacl-star#100]
There are a couple issues in vec128.h.

- [x] arm neon doesn't compile (first part of the fix is in #89)
`/vec128.h:198:57: error: ‘vec {aka struct <anonymous>}’ has no member named ‘vec_xor’ `
- [x] On intel the `_mm_shuffle` is broken, i.e `n%4` has to be constant
`vec128.h:87:20: error: the last argument must be an 8-bit immediate
     r.v = ((vec128)_mm_shuffle_epi32((__m128i)x.v, _MM_SHUFFLE((3 + n) % 4, (2 + n) % 4, (1 + n) % 4, n % 4)));`
- [ ] The code currently supports only SSSE3. It should be possible to make this work with SSE2 and without SSSE3 so that there's an option for people without SSSE3 to use the vectorised version.
- [ ] `__SSSE3__` is not defined for GCC.
- [x] `/usr/lib/gcc/aarch64-linux-gnu/5/include/arm_neon.h:22755:10: error: argument 3 must be a constant immediate`.  Argument 3 in `vsriq_n_u32` must be a constant immediate.
- [x] `__attribute__ ((vector_size (16)))` is a GCC extension and not valid C.

There might be more but this is as far as I got.

**Comment by franziskuskiefer** [comment]
There are only two points open here.
* We work around the `__SSSE3__` in the NSS build system. Not sure if that's something you want to fix here as well.
* An SSE2 version would be nice, but involves writing new code. Not sure if it's worth the effort.

**Comment by beurdouche** [comment]
Marina @polubelova and Karthik @karthikbhargavan have a lock on Lib.IntVector.fst so I am assigning this to you. If it is not relevant anymore, please close the issue.
