### ISSUE TITLE
Using pre-compiled FStar binaries with master branch

### ISSUE THREAD

**Issue by jnchzy** [project-everest/hacl-star#137]
Thank you very much. I have replaced fstar.exe by fstar_0.9.6.0_Windows_x64. Before I used fstar.exe of fstar_0.9.5.0_Windows_x64. But there are still some questions. The errors are showed in the following figure. I don't know the reason. I am looking forward for your answer. Thank you very much.
![image](https://user-images.githubusercontent.com/20393374/50881958-3d357a00-141e-11e9-95a5-b539dc683666.png)

**Comment by s-zanella** [comment]
Which branch of `hacl-star` are you on? If it's `master`, then it's unlikely to work with FStar v0.9.6.0.
Please see #138 for guidance on which branches to use.

**Comment by s-zanella** [comment]
We re-enabled weekly binary builds: https://github.com/FStarLang/binaries/tree/master/weekly
These binaries are kept up to date with changes in FStar, but still aren't guaranteed to work without any other commit hash than the one they were built from.
