### ISSUE TITLE
How to generate C code

### ISSUE THREAD

**Issue by newuser1212** [project-everest/hacl-star#139]
I am trying to use the generated C code in the snapshots/Hacl-c folder. Looking at jsut the C code and I have no idea how to use them. Can anyone point me to any sample codes that utilizes any of the primitive? For example using of the Sha256 Hash function. Thanks very much in advance.

**Comment by s-zanella** [comment]
F* is a general-purpose language, while Vale and Low* are _domain-specific languages_ embedded in F*.
- Low* is shallowly embedded, meaning that you don't need any special syntax to write Low* programs. Low* programs are F* programs written in an appropriate subset of the language that can be translated to C using the KreMLin compiler.
- Vale is deeply embedded, meaning that Vale programs are values of a datatype defined in F* to represent assembly programs, and are given a semantics via an interpreter writen in F*. Although you can write Vale programs directly as terms in F*, the Vale tool provides a more convenient syntax to write assembly programs that get translated to their representation in F*.

**Comment by newuser1212** [comment]
Thanks for the reply. 

I am looking to attempt to learn and write a primitive/algo myself just for better understanding. What is the best way to go about doing it? 
I tried looking at the codes for other implementation and specs such as SHA2's but found it pretty hard to comprehend.

**Comment by newuser1212** [comment]
Thanks for the tutorials, currently checking them out.

I would say what I cannot really understand is actually more towards the whole structure of eventually deriving a verified C code. 
For example, from my understanding, the "Hacl.Hash.Core.SHA2.fst" is verified against the "Spec.SHA2.fst". But then while translating it to C using the KremLin tool, the specs as well as the proofs are erased. So how does the C code also embed the specs and proof properties within as they are already erased? Does the KremLin tool converts the spec/proofs into certain C code and add it in?

**Comment by s-zanella** [comment]
There is no need to embed the specifications and proofs in the generated C code. They have no computational meaning. 
As long as the translation from Low* to C preserves the semantics of the program, the program specified and proven correct in Low* and the C program generated by KreMLin behave the same, and thus the proofs _transfer_ to the C program. 
There is a paper that proves that the KreMLin translation preserves the C semantics and explains how the whole process works in much more detail: [Verified Low-level Embedded Programming in F*](https://arxiv.org/pdf/1703.00053.pdf)

**Comment by newuser1212** [comment]
Hi there,

With reference to #35, I realized that the hacl-star is not the same as the `fstar-master` branch, and is most likely the `master` branch. Is there anyway to get a running image with the `fstar-master` branch? 

In addition, how do you get the `F* mode Emacs ` running in the same image? 

After reading through the tutorials and papers I really do want to get started on attempting to write my own verified primitive, but this initial setting up is sort of killing me. I tried building from source but it just seems to be always failing (dependencies, make, etc). 
I am currently using the `fstarlang/fstar-emacs ` docker but it does not include the additional libs for HACL and I do want to compile the HACL codes as mentioned above. 

Thank you very much in advance.
