### ISSUE TITLE
Performance tests under CI

### ISSUE THREAD

**Issue by jkzinzindohoue** [project-everest/hacl-star#14]
This needs to happen for Windows and Linux, to fully test the generated code for GCC/CLANG, CompCert and MSVC.

Statistics could automatically be generated from performance tests.

**Comment by jkzinzindohoue** [comment]
Snapshot generation is now under continuous integration, still need to add the unit-tests.

**Comment by beurdouche** [comment]
Complicated issue, running the code in userspace with a CPU loaded context is not useful.
I have a solution by disabling CPU interrupts, preemption and shut off other cores... but it needs to be on a Linux box. Then some script must compare with previous performance... That is a long shot...

**Comment by beurdouche** [comment]
We'll track that under https://github.com/project-everest/hacl-star/issues/147
