### ISSUE TITLE
Blake2 Implementations

### ISSUE THREAD

**Issue by georgio** [project-everest/hacl-star#152]
Hello,

Thank you for the incredible work you have been doing.

While checking out your new [post](https://github.com/project-everest/hacl-star/blob/fstar-master/README.EverCrypt.md) for EverCrypt I noticed that you listed Blake2 as a supported hash function [here](https://github.com/project-everest/hacl-star/blob/fstar-master/README.EverCrypt.md#algorithms-supported-by-evercrypt) but was unable to find the source code to your implementations.

I would like to ask if I could be linked to where the code might be located, or, should it still be a work in progress, if you are planning on releasing the implementations soon.

Thanks again!

**Comment by karthikbhargavan** [comment]
We have a verified implementation of blake2s here: 
https://github.com/project-everest/hacl-star/tree/_dev/code/blake2s <https://github.com/project-everest/hacl-star/tree/_dev/code/blake2s>

Check with @beurdourche on the exact status.
He can help you get at the right code for blake2B and blak2s

-Karthik

**Comment by georgio** [comment]
@karthikbhargavan 

Thank you for your reply. I have been trying to compile C code from the F* implementations in the branch you have linked me to since last week, but unfortunately did not succeed.

Were you able to achieve this task or is Blake2s still under development?

cc
@beurdouche

**Comment by beurdouche** [comment]
The code Blake2s code is fine and ready for use in `code/blake2s`, the `blake2b` is still a work in progress in `code/experimental/blake2b`.
I sent the code a few weeks ago to Nadim and I seem to remember that you guys are already using it by now... :)
