### ISSUE TITLE
Failing Assertion

### ISSUE THREAD

**Issue by parkerscott1** [project-everest/hacl-star#162]
Hi,

I am trying to implement the horner's polynomial method and am facing some difficulty. Is there something wrong with my code or is there a bug? 

```
type threshold:nat = 3

  
  
let horner_inner (polynomial:lseq nat threshold)  (xvalue:nat)(i:nat{i<3})  (a:nat) : Tot nat =
	let a = a*xvalue + polynomial.[i] in
	a

let horner (polynomial:lseq nat threshold) (xvalue:nat) (a:nat) : Tot nat =
  let a =  polynomial.[0] in
  //repeati2 is similar to repeati except it starts with i=1 instead of 0
  repeati2 3 (horner_inner polynomial xvalue) a
  
unfold let polylist: list nat =
  [2; 1; 3]
  
  
let polyseq:lseq nat 3 =
  assert_norm (List.Tot.length polylist== 3);
  of_list polylist
 ```

The following assertions are failing.. but it should be going through though. 
```  
//24 is the expected result of the assertion
let _ = assert (horner polyseq 3 0 > 0) 
let _ = assert (horner polyseq 3 0 <> 0)  
let _ = assert (horner polyseq 3 0 = 24) 
```

But this assertion is going through.
```
let _ = assert (horner polyseq 3 0 >= 0) 
```

**Comment by s-zanella** [comment]
You should use `assert_norm` rather than `assert` for computation-heavy proofs. Using `assert_norm` all failing assertions are proved. 

To prove them without normalization, Z3 would need to unfold the recursive definition of `repeati2` (this requires `fuel >= 3`). On top of that, `of_list` (which is deprecated) is defined as opaque to Z3 and you'll need to explicitly apply a lemma to relate `polyseq` to `polylist` (i.e. `Seq.lemma_list_seq_bij polylist`), or use `Seq.createL` instead of `of_list` that does this for you.

**Comment by parkerscott1** [comment]
Sorry but I tried using the ```assert_norm```, set the ```fuel``` and changed to using ```Seq.createL``` instead. I switched to using ```repeati``` instead of my own ```repeati2``` but the assertions are still failing . It should be going through for at least 
```
let _ = assert_norm (horner polyseq 3 0 > 0) 
let _ = assert_norm (horner polyseq 3 0 <> 0) 
```
Is there something I am not seeing?

**Comment by s-zanella** [comment]
Can you provide the full module you're working with? How did you define `repeati2`?

Switching to `Lib.LoopCombinators.repeati` won't help because it's definition is hidden behind the interface of `Lib.LoopCombinators` and so you'll have to apply a lemma to unfold it; see https://fstar.zulipchat.com/#narrow/stream/184683-questions-and.20help/topic/Loop.20Combinators/near/160811710 (behind a registration wall). Same if you defined `repeati2` in terms of `Lib.LoopCombinators.repeat_right`. 

I was trying with a local definition of `repeati2` and that's probably why the assertions are provable for me.

Side note: `assert (horner polyseq 3 0 >= 0)` follows directly from the type of `horner`.

**Comment by parkerscott1** [comment]
This is what I have currently. 

```
module Test
#set-options "--initial_fuel 10 --initial_ifuel 10"

open Lib.IntTypes
open Lib.Sequence
open Lib.ByteSequence
open FStar.Mul
open Lib.LoopCombinators

let horner_inner (polynomial:lseq FStar.UInt64.t threshold)  (xvalue:FStar.UInt64.t)(i:nat{i<3})  (a:FStar.UInt64.t) : Tot FStar.UInt64.t =
	a *. xvalue +. polynomial.[i]

	
let horner (polynomial:lseq FStar.UInt64.t threshold) (xvalue:FStar.UInt64.t) (a:FStar.UInt64.t) : Tot FStar.UInt64.t =
  let a =  polynomial.[0] in
  repeati2 3 (horner_inner polynomial xvalue) a
  //repeati 3 (horner_inner polynomial xvalue) a
  
unfold let polylist: list FStar.UInt64.t =
  [2uL;1uL;3uL]

let polyseq:lseq FStar.UInt64.t 3 =
  assert_norm (List.Tot.length polylist == 3);
  createL polylist  

let _ = assert_norm (horner polyseq 3uL 0uL = 24uL)
let _ = assert_norm (horner polyseq 3uL 0uL  > 0uL)

```

For ```repeati2```, I just added these in the ```Lib.LoopCombinators.fsti``` and ```Lib.LoopCombinators.fst``` modules.

In ```Lib.LoopCombinators.fsti``` :

```
val repeat_gen2:
    n:nat
  -> a:(i:nat{i <= n} -> Type)
  -> f:(i:nat{i < n} -> a i -> a (i + 1))
  -> acc0:a 0
  -> a n

val unfold_repeat_gen2:
    n:nat
  -> a:(i:nat{i <= n} -> Type)
  -> f:(i:nat{i < n} -> a i -> a (i + 1))
  -> acc0:a 0
  -> i:nat{i < n}
  -> Lemma (repeat_gen (i + 1) a f acc0 == f i (repeat_gen i a f acc0))
	
	

val repeati2:
    #a:Type
  -> n:nat
  -> f:(i:nat{i < n} -> a -> a)
  -> acc0:a
  -> a


val unfold_repeati2:
    #a:Type
  -> n:nat
  -> f:(i:nat{i < n} -> a -> a)
  -> acc0:a
  -> i:nat{i < n}
  -> Lemma (repeati2 #a (i + 1) f acc0 == f i (repeati2 #a i f acc0))

```

In ```Lib.LoopCombinators.fst``` :

```
let repeati2 #a n f acc0 =
  repeat_gen2 n (fixed_a a) f acc0
  
let repeat_gen2 n a f acc0 =
  repeat_right 1 n a f acc0
```

**Comment by s-zanella** [comment]
The interface `Lib.LoopCombinators.fsti` hides your definition of `repeati2`, so it can't be normalized.
There are good reasons to hide the definition of `repeati` because its main use is in specifications where uncontrolled unfolding is undesirable. That means the assertions in your module are not provable by normalization (or unfolding by Z3 with any amount of fuel). If your main use of `repeati2` is in proofs that require computation then you should make its definition as a recursive function transparent.

**Comment by s-zanella** [comment]
For experimenting, you can break the abstraction of `Lib.LoopCombinators.fsti` by declaring your module a friend of `Lib.LoopCombinators` with `friend Lib.LoopCombinators`. You need to have an interface for your module to do this.

**Comment by parkerscott1** [comment]
I am actually writing for a specification. Do you recommend the ```friend``` route or defining locally as you have previously mentioned?

On a side note, I realised I should have been using Int64 instead as there are negative values involved.
However, this does not seem to work.

```
let horner_inner (polynomial:lseq FStar.Int64.t threshold)  (xvalue:FStar.Int64.t) (i:nat{i<3})  (a:FStar.Int64.t) : Tot FStar.Int64.t =
	a *. xvalue +. polynomial.[i]
```

with the error that I have no idea how to resolve. 

```
Test.fst(43,1-43,7): (Error 66) Failed to resolve implicit argument ?15 of type Lib.IntTypes.secrecy_level introduced for Instantiating implicit argument in application
1 error was reported (see above)
```

**Comment by parkerscott1** [comment]
I think I figured it out regarding the Int64. 
```
type threshold:nat

let horner_inner (polynomial:lseq FStar.Int64.t threshold{forall threshold. FStar.Int64.(polynomial.[threshold] <^ 50L)}  )  (xvalue:FStar.Int64.t{FStar.Int64.(xvalue <^50L /\ xvalue >^ 2L)}) (i:nat{i<3})  (a:FStar.Int64.t{FStar.Int64.(a <^ 50L /\ a >^ 2L	)}) : Tot FStar.Int64.t =
	FStar.Int64.(a *^ xvalue +^ polynomial.[i])
```

**Comment by parkerscott1** [comment]
Is there any workaround if I really do need signed integers? For my use case I will definitely hit negative integers. These are just the shell of the loop functions. 

```
//outer for loop
let lagrangePolationOuter (threshold:uint64) (resultlist:(lseq (lseq uint64 2) 5)) (i:nat{i<3}) : Tot uint64 = 
	let term = (resultlist.[i]).[1] in
	term

//inner loop
let lagrangePolationInner(threshold:nat{threshold =3}) (resultlist:(lseq (lseq uint64 2) threshold)) (xvalue:uint64) (term:uint64) (i:nat{i<threshold}) (j:nat{j<threshold}) (result:uint64) : Tot uint64 =
	if not (j=i) then
		//the line below is the one that requires negative integers
                let term = (term *. (xvalue -. (resultlist.[j]).[0])) /. ((resultlist.[i]).[0] -. (resultlist.[j]).[0]) in 		
		//let term = FStar.Int64.int_to_t ((term *. (xvalue -. (resultlist.[j]).[0])) /. ((resultlist.[i]).[0] -. (resultlist.[j]).[0])) in 		
	
	let result = term +. result in
	result

```

Another problem I am wondering about is when I use the ```if not (j=i) then``` statement, it always return ```Prims.unit type```. Why is that so?

**Comment by s-zanella** [comment]
There is no easy workaround for using signed integers together with Hacl* library. You can roll out your own extension of `Lib.IntTypes`, or not use Hacl* library and use the `FStar.ConstantTime.Integers` and `LowStar` libraries instead.

As for the typing error,
```FStar
let f b = 
  if b then
      let result = 1 in
  result
```
is parsed as
```FStar
let f b = 
  if b then
      let result = 1 in
      result
  else ()
```

**Comment by parkerscott1** [comment]
I think I will take the ```FStar.ConstantTime.Integers``` route. I will head over to the FStar side and clarify with them instead. 

Thank you for all your help really appreciate it.

**Comment by newuser1212** [comment]
Hi @s-zanella,

I tried to write a separate module to be extracted to OCaml for the specifications. However, I still am not able to properly verify the assertions after adding ```friend```. 

SSSSpec.fst:
```
module SSSSpec
#set-options "--initial_fuel 100 --initial_ifuel 50"

open Lib.IntTypes
open Lib.Sequence
open Lib.ByteSequence
open FStar.Mul
open Lib.LoopCombinators

open Lib.IntTypes
open FStar.Mul

let theta0 (threshold:size_nat{threshold>=3}) (polynomial:lseq uint64 threshold)  (xvalue:uint64) (i:nat{i<length polynomial}) (result:lseq uint64 1) : Tot (lseq uint64 1) = 
    result.[0] <- result.[0] *. xvalue +. polynomial.[i]

let theta0_repeat (threshold:size_nat{threshold>=3}) (polynomial:lseq uint64 threshold) (xvalue:uint64) (result:lseq uint64 1) : Tot (lseq uint64 1) =
  let result = result.[0] <-  polynomial.[0] in
  repeati threshold (theta0 threshold polynomial xvalue) result

let generateShares (participants:size_nat{participants>2}) (threshold:size_nat{threshold>=3 /\ participants > threshold}) (polynomial:lseq uint64 threshold) (result:lseq uint64 1) (i:nat{i<participants}) (resultlist:lseq (lseq uint64 2) participants) : Tot (resultlist:lseq (lseq uint64 2) participants) =
	let x:uint64 =(theta0_repeat threshold polynomial (nat_to_uint i) result).[0] in
	let tmpList = [nat_to_uint i ; x] in
	let tmpSeq = of_list tmpList in
	resultlist.[i] <- tmpSeq 
  
let repeat_genshares (participants:size_nat) (threshold:size_nat{threshold>=3 /\ participants > threshold}) (polynomial:lseq uint64 threshold) (result:lseq uint64 1) (resultlist:lseq (lseq uint64 2) participants) : Tot (resultlist:lseq (lseq uint64 2) participants) =	
	repeati2 participants (generateShares participants threshold polynomial result) resultlist

let sss_shares (participants:size_nat{participants>2}) (threshold:size_nat{threshold>=3 /\ participants > threshold}) (polynomial:lseq uint64 threshold): Tot (resultlist:lseq (lseq uint64 2) participants) = 
	let result = create 1 (u64 0) in
	let resultList = create participants (create 2 (u64 0)) in
	repeat_genshares participants threshold polynomial result resultList
```
SSSSpecTest.fsti :
```
module SSSSpecTest
#set-options "--initial_fuel 50 --initial_ifuel 50"

open FStar.Mul
open Lib.IntTypes
open Lib.RawIntTypes
open Lib.Sequence
open FStar.All

``` 


SSSSpecTest.fst : 
```
module SSSSpecTest
#set-options "--initial_fuel 100 --initial_ifuel 50"
friend Lib.LoopCombinators

//2x^2 + 3x + 5  
let polynomial = List.Tot.map u64_from_UInt64 [2uL; 3uL; 5uL]

let xvalue:uint64 = u64_from_UInt64 2uL
let result = List.Tot.map u64_from_UInt64 [0uL]



let polySeq = of_list polynomial 
let resultSeq = of_list result
#reset-options "--z3rlimit 50 --max_fuel 0 --max_ifuel 0 --using_facts_from '* -FStar.Seq'"

let printstuff uint64 : ML unit = 
  let b = SSSSpec.sss_shares 5 3 polySeq in
  let c = b.[0] in
  let d = c.[0] in
  let test = u64_from_UInt64 0uL in
  //let x = assert_norm(uint_v d = 0) in
  //let x = assert_norm(uint_v d <> 0) in
  //let y = assert_norm(FStar.UInt64.eq_mask (b) (u64_from_UInt64(4uL))) in 
  //let z = uintv_extensionality #U64 #SEC (d) (test) in
  IO.print_string "d"
  

let test () = 
  IO.print_string "==========================\n";
  printstuff
```

**Comment by s-zanella** [comment]
Hi @newuser1212 

What assertions do you expect to be provable? 

At first sight, I see two issues with the code above:

1. Setting `--using_facts_from '* -FStar.Seq'` disables encoding the `FStar.Seq` theory to the Z3. The normalizer by itself doesn't reduce expressions like `Seq.index (Seq.of_list [0]) 0`, so to prove things about expressions like these you'll need to rely on Z3. 

2. Some definitions in `Lib.Sequence` are hidden by the interface. Consider making your module a `friend` of `Lib.Sequence` so that the definitions there can be unfolded to definitions in `FStar.Seq`.

The example code got to a point where it's too complex for an outsider like me to analyze---it involves 3 different modules and 5 different files. If you still can't resolve the issue, please consider writing a self-contained minimal example that has the same behavior.

**Comment by newuser1212** [comment]
Hi @s-zanella,

Essentially I am trying to test the value obtained by the test case in ```SSSSpecTest.fst```. My assertions are 
 trying to compare the secret int by casting/comparing it using ```uint_v``` and ```uintv_extensionality``` but the assertions are failing. I am not sure whether the problem lies with my program or I am just using the wrong method in proving secret int. Is this the correct way to test on secret int?

**Comment by newuser1212** [comment]
Here is a simplified, minimal version : 

Spec.fst
```
let count (polynomial:lseq uint64 1)  (xvalue:uint64) (result:lseq uint64 1) : Tot (lseq uint64 1) = 
    result.[0] <- (result.[0] *. xvalue +. polynomial.[0])
```

Test.fst
```
let polynomial = List.Tot.map u64_from_UInt64 [2uL]
let polySeq = of_list polynomial 
let result = List.Tot.map u64_from_UInt64 [0uL]
let resultSeq = of_list result

let xvalue:uint64 = u64_from_UInt64 2uL
	
let printstuff  =         
	let b = Spec.count polySeq xvalue resultSeq in    //it should be 0 * 2 + 2 = 2
 	let c  = b.[0] in
	uintv_extensionality #U64 #SEC (c) (xvalue)  //assert fails
```


However, when I test it with another example, it works.

Spec.fst
```
let count(xvalue:uint64) (term:uint64) : Tot uint64 =
	let result = term +. xvalue in
	result
```

Test.fst
```
let xvalue:uint64 = u64_from_UInt64 2uL
let term:uint64 = u64_from_UInt64 3uL

let printstuff  = 
  let c = Spec.count xvalue term in
  let test = u64_from_UInt64 5uL in
 uintv_extensionality #U64 #SEC (c) (test)
```

**Comment by s-zanella** [comment]
You have 3 assertions in `SSSSpecTest.fst`:

- `assert_norm(uint_v d = 0)` it's provable when adding `friend Lib.Sequence` and removing
`--using_facts_from '-FStar.Seq'`
- `assert_norm(uint_v d <> 0)` it's false
- `assert_norm(FStar.UInt64.eq_mask b (u64_from_UInt64(4uL)))` it's ill-typed

I'm assuming you're using the `dev` branch. `fstar-master` is slightly behind and misses a proper injectivity lemma for `uint_v` (https://github.com/project-everest/hacl-star/blob/dev/lib/Lib.IntTypes.fsti#L169).
You don't need to let-bind the result of an assertion, which is `()`, just use `;`.

**Comment by s-zanella** [comment]
Thanks for trying to minimize the example. In the future,
- Give the full files, including any prelude. I can guess which modules you're opening, but I can't tell if you have any `friend` declarations. 
- There is no need for two separate files, you could have merged `Spec.fst` and `Test.fst`
- Please use ```FStar to get syntax-highlighting

This works
- `Test.fst`:
```FStar
module Test

open Lib.IntTypes
open Lib.Sequence

friend Lib.IntTypes
friend Lib.Sequence

let count (polynomial:lseq uint64 1) (xvalue:uint64) (result:lseq uint64 1) : lseq uint64 1 = 
  result.[0] <- result.[0] *. xvalue +. polynomial.[0]

let polySeq : lseq uint64 1 = of_list [u64 2]
let resultSeq : lseq uint64 1 = of_list [u64 0]
let xvalue = u64 2

#reset-options "--max_fuel 0 --max_ifuel 0"

let test =  
  let b = count polySeq xvalue resultSeq in
  let c = b.[0] in
  assert_norm (uint_v c == 2)
```
- `Test.fsti`
```FStar
module Test
```

**Comment by newuser1212** [comment]
I didn't realize I wasn't using the FStar syntax-highlighting, so sorry about that. 
I managed to get the assertions to work thus far. When I run the verification in the command line, it does verify. 

However, when I attempt to compile it to OCaml as an executable, I was stuck in the creation of the ```.checked``` files for ```Lib.LoopCombinators```, which I have defined the ```repeati2``` function if u recall. How did the verification go through if my definitions seem to be faulty?

Sorry to paste this again but do you mind helping me see how to properly define the repeati2? I made some changes from the prior post. (the one from before also couldn't generate the ```.checked``` file.

In ```Lib.LoopCombinators.fsti```
```FStar
val repeat_right2:
    lo:nat{lo=1}
  -> hi:nat{lo <= hi}
  -> a:(i:nat{lo <= i /\ i <= hi} -> Type)
  -> f:(i:nat{lo <= i /\ i < hi} -> a i -> a (i + 1))
  -> acc:a lo
  -> Tot (a hi) (decreases (hi - lo))


val repeati2:
    #a:Type
  -> n:nat
  -> f:(i:nat{i < n} -> a -> a)
  -> acc0:a
  -> a
  
  
(** Unfolding one iteration *)
val unfold_repeati2:
    #a:Type
  -> n:nat
  -> f:(i:nat{i < n} -> a -> a)
  -> acc0:a
  -> i:nat{i < n}
  -> Lemma (repeati2 #a (i + 1) f acc0 == f i (repeati2 #a i f acc0))
```

In ```Lib.LoopCombinators.fst```
```FStar
let fixed_aa (a:Type) (i:nat{i<=1}) = a


let rec repeat_right2 lo hi a f acc =
  if lo = hi then acc
  else f (hi - 1) (repeat_right2 lo (hi - 1) a f acc)

let repeat_gen2 n a f acc0 =
  repeat_right2 1 n a f acc0  
  
let repeati2 #a n f acc0 =
  repeat_gen2 n (fixed_aa a) f acc0

  
let unfold_repeat_gen2 n a f acc0 i = ()
(* // Proof when using [repeat_left]:
  repeat_left_right 0 (i + 1) a f acc0;
  repeat_left_right 0 i a f acc0
*)
  
  
let unfold_repeati2 #a n f acc0 i =
  unfold_repeat_gen2 n (fixed_aa a) f acc0 i
```

**Comment by s-zanella** [comment]
F* lax-typechecks the dependencies of the module you're verifying. In this case, your module depends on `Lib.LoopCombinators.fsti` (but not `Lib.LoopCombinators.fst`). `Lib.LoopCombinators.fsti` lax-typechecks (it also fully typechecks), so you're module verifies. It's only when attempting to fully typecheck `Lib.LoopCombinators.fst` that F* actually checks that the definitions you added verify.

I don't see the point of redefining specialized versions of `repeat_right` and `fixed_a`. 
I think the typing error that you get when checking your definition of `repeati2` is self-explanatory: 

```expected type hi: nat{1 <= hi}; got type nat``` 

The type of `n` in the declaration of `repeati2` is not strong enough.

**Comment by newuser1212** [comment]
Thanks for clearing up my doubts, but there are still some stuff that I am stuck with. (I tried to minimize the example code as much as I could)

1) Is it possible to define sort of a nested buffer? I read that buffers are more efficient during extraction to C and I am trying to mimic a nested sequence in my specifications. Below is a example of a use case.

```Testspec.fst```
```FStar
module Testspec

open Lib.IntTypes
open Lib.Sequence

let test (nestedSeq:lseq (lseq uint64 2) 5) : Tot (lseq (lseq uint64 2) 5) =
	let nestedSeq = nestedSeq.[0] <- nestedSeq.[1] in
	nestedSeq
```

```Testimpl.fst```
```FStar

module Testimpl

open FStar.HyperStack.All
open FStar.HyperStack
open FStar.HyperStack.ST
open Lib.IntTypes
open Lib.Buffer
module S = Testspec

val test:
	x:lbuffer uint64 2ul
 	 -> resultlist:lbuffer (lbuffer uint64 2ul) 5ul //this does not tally with the nested sequence type
	 -> Stack unit
    (requires fun h -> live h resultlist)
    (ensures fun h0 r h1 -> 
      modifies (loc resultlist) h0 h1 /\ 
      as_seq h1 resultlist == S.test  (as_seq h0 resultlist))
```


2) Another question, the below code is failing with ```Failed to resolve implicit argument ?55 of type Lib.IntTypes.size_t introduced for Instantiating implicit argument in application ``` but I can't seem to figure out how to resolve it. It seems to be the modification to the buffer before it goes through the repeat function, which uses ```as_seq h0 b```.


```Test2spec.fst```
```FStar 
module Test2spec

open Lib.IntTypes
open Lib.Sequence
open FStar.Mul
open Lib.LoopCombinators

let test2 (a:lseq uint64 5) (x:nat{x<5 }) (b:lseq uint64 5) : Tot (lseq uint64 5) = 
 b.[x] <- a.[x]
 
let test2_repeat (a:lseq uint64 5) (b:lseq uint64 5) : Tot (lseq uint64 5) =
 let b = b.[0] <- b.[1] in //I think this is the line that causes the error
  repeati 5 (test2 a) b
```

```Test2impl.fst```
```FStar
module Test2impl

open FStar.HyperStack.All
open FStar.HyperStack
open FStar.HyperStack.ST
open FStar.Mul
open LowStar.Buffer
open LowStar.BufferOps
open Lib.IntTypes
open Lib.Buffer
module ST = FStar.HyperStack.ST
module Loop = Lib.LoopCombinators
module S = Test2spec

val test2:
  a:lbuffer uint64 5ul
  -> x:uint_t U32 PUB {v x<5}  
 -> b:lbuffer uint64 5ul 
  -> Stack unit
    (requires fun h -> live h a /\ live h b /\ disjoint a b)
    (ensures fun h0 r h1 -> 
      modifies (loc b) h0 h1 /\
            as_seq h1 b == S.theta1 (as_seq h0 a) (v x) (as_seq h0 b))      
  
let test2 a x b =
  b.(x) ← a.(x)

val test2_repeat:
  a:lbuffer uint64 5ul
  -> b:lbuffer uint64 5ul
  -> Stack unit
    (requires fun h -> live h a /\ live h b /\ disjoint a b)
    (ensures fun h0 r h1 -> 
      modifies (loc b) h0 h1 /\ 
      as_seq h1 b == S.test2 (as_seq h0 a) (as_seq h0 b))
 
let theta1_repeat a b =
 let b = b.(0ul) <- b.(1ul) in	
  [@ inline_let]
 let spec h0 = S.test2 (as_seq h0 a) in
 let h0 = ST.get() in 
 loop1 (h0) (5ul) (b) (spec)
  (fun x -> 
    Loop.unfold_repeati 5 (spec h0) (as_seq h0 b) (v x);   
    theta1 a x b
  )
```

**Comment by newuser1212** [comment]
And for the previous ```repeati2``` definitions, I think I managed to figured it out with the proper types so I will just leave it here in case anyone is having the same problem.


```Lib.LoopCombinators.fsti```
```FStar
val repeati2:
    #a:Type
  -> n:nat{n >= 1}
  -> f:(i:nat{i < n /\ i >=1} -> a -> a)
  -> acc0:a
  -> a
  
(** Unfolding one iteration *)
val unfold_repeati2:
    #a:Type
  -> n:nat{n >= 1} 
  -> f:(i:nat{i < n /\ i>=1} -> a -> a)
  -> acc0:a
  -> i:nat{i < n /\ i <> 0}
  -> Lemma (repeati2 #a (i + 1) f acc0 == f i (repeati2 #a i f acc0))
```

```Lib.LoopCombinators.fst```
```FStar
let repeat_gen2 n a f acc0 =
  repeat_right 1 n a f acc0    
  
let repeati2 #a n f acc0 =
  repeat_gen2 n (fixed_a a) f acc0
  
let unfold_repeat_gen2 n a f acc0 i = ()  
  
let unfold_repeati2 #a n f acc0 i =
  unfold_repeat_gen2 n (fixed_a a) f acc0 i
```

```Lib.Buffer.fsti```
```FStar
let loop1_inv1
    (h0:mem)
    (n:size_t)
    (b: Type)
    (blen: size_t)
    (write:lbuffer b blen)
    (spec:(mem -> GTot (i:size_nat{i < v n /\ i > 0} -> Seq.lseq b (v blen) -> Seq.lseq b (v blen))))
	(i:size_nat{i <= v n /\ i > 0})
    (h:mem):
    Type0
=
  modifies1 write h0 h /\
  as_seq h write == Loop.repeati2 i (spec h0) (as_seq h0 write)

  
(** Loop combinator specialized to modifying a single buffer [write] *)
inline_for_extraction noextract
val loop11:
    #b:Type
  -> #blen:size_t
  -> h0:mem
  -> n:size_t
  -> write:lbuffer b blen
  -> spec:(mem -> GTot (i:size_nat{i < v n /\ i >= 1} -> Seq.lseq b (v blen) -> Seq.lseq b (v blen)))
  -> impl:(i:size_t{v i < v n /\ v i > 0} -> Stack unit
     (requires loop1_inv1 h0 n b blen write spec (v i))
     (ensures  fun _ _ -> loop1_inv1 h0 n b blen write spec (v i + 1))) ->
  Stack unit
    (requires fun h -> h0 == h)
    (ensures  fun _ _ -> loop1_inv1 h0 n b blen write spec (v n))
```

```Lib.Buffer.fst```
```FStar
let loop11 #b #blen h0 n acc spec impl =
  let inv h i = loop1_inv1 h0 n b blen acc spec i h in
  Lib.Loops.for (size 1) n inv impl
```

**Comment by s-zanella** [comment]
You don't need to modify the library to do any of this. 
Your combinators just shift indices by 1 and they can readily be defined in terms of the existing `repeat_right` and `loop1` combinators. For instance,

```FStar
open Lib.LoopCombinators

val repeati2:
    #a:Type
  -> n:pos
  -> f:(i:pos{i < n} -> a -> a)
  -> acc0:a
  -> a
let repeati2 #a n f acc0 =
  repeat_right 1 n (fixed_a a) f acc0

val unfold_repeati2:
    #a:Type
  -> n:nat{n >= 1} 
  -> f:(i:pos{i < n} -> a -> a)
  -> acc0:a
  -> i:pos{i < n-1}
  -> Lemma (repeati2 #a (i + 1) f acc0 == f i (repeati2 #a i f acc0))
let unfold_repeati2 #a n f acc0 i = 
  unfold_repeat_right 1 n (fixed_a a) f acc0 i
```

Please open different issues for your follow-up questions. They have little to do with the original question and this issue has been long closed.

**Comment by newuser1212** [comment]
Hi @s-zanella, sorry to revisit this topic, but the ```loop1``` combinator does not seem to match with the ```unfold_repeati2``` type. I tried to minimize my example into one single file. 
Changing the ```i``` variable to ```i:size_nat{i<5 /\ i>0}```, which should be the same as the currently defined one, does not match too. How do I define it?

```FStar 
module Testimpl
open FStar.HyperStack.All
open FStar.HyperStack
open FStar.HyperStack.ST
open FStar.Mul
open LowStar.Buffer
open LowStar.BufferOps
open Lib.IntTypes
open Lib.Buffer
open Lib.Sequence
open Lib.LoopCombinators
module ST = FStar.HyperStack.ST
module Loop = Lib.LoopCombinators

let func1_spec (i:pos{i < 5}) (a:lseq uint64 5) : Tot (lseq uint64 5) = 
    let a = a.[i] <- a.[i] +. a.[i] in
	a

let func2_spec (a:lseq uint64 5) : Tot (lseq uint64 5) =
  repeati2 5 (func1_spec) a	
	
		
val func1:
  i:size_t {v i < 5 /\ v i > 0}
  -> a:lbuffer uint64 (5ul)  
  -> Stack unit
	(requires fun h -> live h a)
	(ensures fun h0 r h1 -> 
	    modifies1 a h0 h1 /\
	    as_seq h1 a == func1_spec (v i) (as_seq h0 a))

let func1 i a =
	a.(i) <- a.(i) +. a.(i)

	
val func2:
	a:lbuffer uint64 (5ul)  
	-> Stack unit
    (requires fun h -> live h a)
    (ensures fun h0 r h1 -> 
	modifies1 a h0 h1 /\
	as_seq h1 a == func2_spec (as_seq h0 a))
  

let func2 a = 
    let spec h0 = func1_spec in
	let h0 = ST.get() in
	loop1 (h0)(5ul)(a)(spec)
	(fun x -> 
	Loop.unfold_repeati2 5 (spec h0) (as_seq h0 a) (v x);
	func1 x a
	)

**Comment by s-zanella** [comment]
Your example is once more not self-contained because it uses your own modified version of `Lib.LoopCombinators` defining `repeati2` and `unfold_repeati2`. 

In the loop, `x` ranges over 0..4 and there is a call to `func1`, which requires `x > 0` so the loop is ill-typed. You need to shift the index accordingly to use the correct range.

How do you prove `func2` depends on whatever `Lib.LoopCombinators` exposes about `repeati2`. At a minimum, you need to relate `repeati2` to `repeati` because the specification of `loop1` is expressed in terms of it.

**Comment by newuser1212** [comment]
Sorry..  I am using the same definition as you suggested last time. 

In Lib.LoopCombinators.fsti
```FStar
val repeati2:
    #a:Type
  -> n:pos
  -> f:(i:pos{i < n} -> a -> a)
  -> acc0:a
  -> a

val unfold_repeati2:
    #a:Type
  -> n:nat{n >= 1} 
  -> f:(i:pos{i < n} -> a -> a)
  -> acc0:a
  -> i:pos{i < n-1}
  -> Lemma (repeati2 #a (i + 1) f acc0 == f i (repeati2 #a i f acc0))
```

In Lib.LoopCombinators.fst
```FStar
let unfold_repeati2 #a n f acc0 i = 
  unfold_repeat_right 1 n (fixed_a a) f acc0 i

let repeati2 #a n f acc0 =
  repeat_right 1 n (fixed_a a) f acc0
```

> In the loop, x ranges over 0..4 and there is a call to func1, which requires x > 0 so the loop is ill-typed. You need to shift the index accordingly to use the correct range.

I get this but to match the type of ```unfold_repeati2``` which requires a ```pos``` while the type of ```loop1``` requires a ```nat```, which includes a 0. I tried to define the ```n``` parameter of ```loop1``` as follows but it fails. 
```FStar
let func2 a = 
    let spec h0 = func1_spec in
	let h0 = ST.get() in
	let tmp:pos = 5 in //this is the extra line i added in
	loop1 (h0)(size tmp)(a)(spec)
	(fun x -> 
	unfold_repeati2 5 (spec h0) (as_seq h0 a) (v x);
	func1 x a
	)
```

**Comment by s-zanella** [comment]
I didn't suggest to modify `Lib.LoopCombinators`, but either to add these definitions in your module or inline them. Clearly what you put in `Lib.LoopCombinators.fsti` is insufficient to complete your proof.

I don't see how the extra line you added can help fix the problem with typing the body of the loop. It's equivalent to what you had before.
