### ISSUE TITLE
Nested buffers

### ISSUE THREAD

**Issue by newuser1212** [project-everest/hacl-star#166]
Is it possible to define sort of a nested buffer? I read that buffers are more efficient during extraction to C and I am trying to mimic a nested sequence in my specifications. Below is a example of a use case.
```Testspec.fst```
```FStar
module Testspec

open Lib.IntTypes
open Lib.Sequence

let test (nestedSeq:lseq (lseq uint64 2) 5) : Tot (lseq (lseq uint64 2) 5) =
	let nestedSeq = nestedSeq.[0] <- nestedSeq.[1] in
	nestedSeq
```

```Testimpl.fst```
```FStar
module Testimpl

open FStar.HyperStack.All
open FStar.HyperStack
open FStar.HyperStack.ST
open Lib.IntTypes
open Lib.Buffer
module S = Testspec

val test:
 	 nestedbuf:lbuffer (lbuffer uint64 2ul) 5ul //this does not tally with the nested sequence type
	 -> Stack unit
    (requires fun h -> live h nestedbuf)
    (ensures fun h0 r h1 -> 
      modifies (loc nestedbuf) h0 h1 /\ 
      as_seq h1 nestedbuf == S.test  (as_seq h0 nestedbuf))
```

**Comment by s-zanella** [comment]
It is possible to define nested buffers; you did it in your code. 
You should use buffers if you intend to use KreMLin extraction. Sequences extract as linked lists, are much less efficient and leak memory.

I don't recommend using nested buffers. Perhaps you can use a representation as a flat buffer. See for instance https://github.com/project-everest/hacl-star/blob/_dev/code/frodo/code/Hacl.Impl.Matrix.fst
