### ISSUE TITLE
Question about loop combinators

### ISSUE THREAD

**Issue by newuser1212** [project-everest/hacl-star#169]
Hi, I was playing around with some form of composite function as with the code below but got the ``` could not prove post-condition``` in ```F_impl.fst```. (This is just an example, I know it can be shorten down to just one function)

```F_spec.fst```
```FStar
module F_spec

open Lib.IntTypes
open Lib.Sequence

let test (a:lseq uint64 2) : (lseq uint64 2) = 
    a.[0] <- a.[1] 
	
let test2 (a:lseq uint64 2)(b:lseq uint64 5) : (lseq uint64 5) = 
	let x:uint64 = (test a).[0] in 
	let b = b.[0] <- x in
	b
```

```F_impl.fst```
```FStar
module F_impl

open FStar.HyperStack.All
open FStar.HyperStack
open FStar.HyperStack.ST
open Lib.IntTypes
open Lib.Buffer
module S = F_spec

val test:
	a:lbuffer uint64 2ul  
	-> Stack unit
	    (requires fun h -> live h a)
	    (ensures fun h0 r h1 -> 
	        modifies1 a h0 h1 /\
		as_seq h1 a == S.test (as_seq h0 a))
		
let test a =
	a.(0ul) <- a.(1ul)
	
val test2:
	a:lbuffer uint64 2ul  
	-> b:lbuffer uint64 5ul
	-> Stack unit
            (requires fun h -> live h a /\ live h b)
            (ensures fun h0 r h1 -> 
                modifies1 a h0 h1 /\ modifies1 b h0 h1 /\
                as_seq h1 a ==S.test2 (as_seq h0 a) (as_seq h0 b) /\
	        as_seq h1 b == S.test2 (as_seq h1 a) (as_seq h0 b))

let test2 a b = 
	push_frame();
	test a;
	b.(0ul) <- a.(0ul);	
	pop_frame()
```

**Comment by aseemr** [comment]
Hi:

The following modified code works, I have added some comments to the changes I made:

```
module F_spec

open Lib.IntTypes
open Lib.Sequence

let test (a:lseq uint64 2) : (lseq uint64 2) = 
    a.[0] <- a.[1] 
	
let test2 (a:lseq uint64 2)(b:lseq uint64 5) : (lseq uint64 5) = 
	//let x:uint64 = test a in //commenting since (test a) has type lseq, and not uint64
	let b = b.[0] <- a.[0] in
	b
```

```
module F_impl

open FStar.HyperStack.All
open FStar.HyperStack
open FStar.HyperStack.ST
open Lib.IntTypes
open Lib.Buffer
module S = F_spec

val test:
	a:lbuffer uint64 2ul  
	-> Stack unit
	    (requires fun h -> live h a)
	    (ensures fun h0 r h1 -> 
	        modifies1 a h0 h1 /\
		as_seq h1 a == S.test (as_seq h0 a))
		
let test a =
	a.(0ul) <- a.(1ul)
	
val test2:
	a:lbuffer uint64 2ul  
	-> b:lbuffer uint64 5ul
	-> Stack unit
            //need disjointness of a and b
            (requires fun h -> live h a /\ live h b /\ disjoint a b)  
            (ensures fun h0 r h1 -> 
                //modifies a h0 h1 /\ modifies b h0 h1 is not the right way to specify the modifies clause
                //since (modifies l h0 h1) where l is a location, says that from h0 to h1 only l changes
                //every other disjoint location remains unmodified
                //with a and b disjoint, (modifies a h0 h1 /\ modifies b h0 h1) is kind of contradictory
                //instead use modifies2
                modifies2 a b h0 h1 /\
                as_seq h1 a == S.test (as_seq h0 a) /\  //changing this postcondition to S.test
	        as_seq h1 b == S.test2 (as_seq h1 a) (as_seq h0 b))

let test2 a b = 
	push_frame();
	test a;
	b.(0ul) <- a.(0ul);	
	pop_frame()
```

**Comment by newuser1212** [comment]
Hi,
Thanks for the detailed reply, I think I have a better understanding of it. However, I tried another example, this time with a loop combinator and followed your style but it does not go through. Am I missing certain additional lemmas to prove the ```repeati``` combinator?

```F_spec.fst```
```FStar
module F_spec

open Lib.IntTypes
open Lib.Sequence
open Lib.LoopCombinators

let test  (a:lseq uint64 3) (inde:nat{i<3}) (b:lseq uint64 3): (lseq uint64 3) = 
    b.[i] <- a.[i]
	
let test2(a:lseq uint64 3)  (b:lseq uint64 3) : (lseq uint64 3) = 
    repeati 2 (test a) b

	
let test3 (a:lseq uint64 3)(b:lseq uint64 3) (c:lseq uint64 3) : (lseq uint64 3) = 
	let b = test2 a b in
	let c = c.[0] <- b.[0] in
	c
```

```F_impl.fst```
```FStar
module F_impl

open FStar.HyperStack.All
open FStar.HyperStack
open FStar.HyperStack.ST
open Lib.IntTypes
open Lib.Buffer
module Loop = Lib.LoopCombinators
module ST = FStar.HyperStack.ST
module S = F_spec

val test:
    a:lbuffer uint64 3ul  
    -> i:size_t{v i < 3}
    -> b:lbuffer uint64 3ul  
    -> Stack unit
	(requires fun h -> live h a /\ live h b /\ disjoint a b)
	(ensures fun h0 r h1 -> 
	    modifies1 b h0 h1 /\
            as_seq h1 b == S.test  (as_seq h0 a) (v i) (as_seq h0 b)) 		
		
let test a i b =
	b.(i) <- a.(i)
	
val test2:
    a:lbuffer uint64 3ul
    -> b:lbuffer uint64 3ul 
    -> Stack unit
    (requires fun h -> live h a /\ live h b /\ disjoint a b)
    (ensures fun h0 r h1 -> 
      modifies1 b h0 h1 /\
      as_seq h1 b ==S.test2 (as_seq h0 a) (as_seq h0 b))
	  
let test2 a b = 
    let spec h0 = S.test (as_seq h0 a)  in
    let h0 = ST.get() in
    loop1 (h0)(2ul) (b) (spec) (fun x -> Loop.unfold_repeati (2) (spec h0) (as_seq h0 b) (v x);   
	test a x b)

val test3:
    a:lbuffer uint64 3ul  
    -> b:lbuffer uint64 3ul
    -> c:lbuffer uint64 3ul
    -> Stack unit
        (requires fun h -> live h a /\ live h b /\ live h c /\ disjoint a b /\ disjoint a c /\ disjoint b c)
        (ensures fun h0 r h1 -> 
            modifies2 b c h0 h1 /\
	  as_seq h1 b ==S.test2 (as_seq h0 a) (as_seq h0 b) /\
	  as_seq h1 c == S.test3 (as_seq h0 a) (as_seq h1 b) (as_seq h0 c))

let test3 a b c = 
	push_frame();
	test2 a b;
	c.(0ul) <- b.(0ul);	
	pop_frame()
```

**Comment by Basse333** [comment]
Then you maight need a certain to make it work, i know that you knows your stuff
________________________________
Från: newuser1212 <notifications@github.com>
Skickat: den 26 juni 2019 05:30:30
Till: project-everest/hacl-star
Kopia: Subscribed
Ämne: Re: [project-everest/hacl-star] Composite Function unable to prove post-condition (#169)


Hi,
Thanks for the detailed reply, I think I have a better understanding of it. However, I tried another example, this time with a loop combinator and followed your style but it does not go through. Am I missing certain additional lemmas to prove the repeati combinator?

F_spec.fst

module F_spec

open Lib.IntTypes
open Lib.Sequence
open Lib.LoopCombinators

let test  (a:lseq uint64 3) (inde:nat{i<3}) (b:lseq uint64 3): (lseq uint64 3) =
    b.[i] <- a.[i]

let test2(a:lseq uint64 3)  (b:lseq uint64 3) : (lseq uint64 3) =
    repeati 2 (test a) b


let test3 (a:lseq uint64 3)(b:lseq uint64 3) (c:lseq uint64 3) : (lseq uint64 3) =
        let b = test2 a b in
        let c = c.[0] <- b.[0] in
        c

F_impl.fst

module F_impl

open FStar.HyperStack.All
open FStar.HyperStack
open FStar.HyperStack.ST
open Lib.IntTypes
open Lib.Buffer
module Loop = Lib.LoopCombinators
module ST = FStar.HyperStack.ST
module S = F_spec

val test:
    a:lbuffer uint64 3ul
    -> i:size_t{v i < 3}
    -> b:lbuffer uint64 3ul
    -> Stack unit
        (requires fun h -> live h a /\ live h b /\ disjoint a b)
        (ensures fun h0 r h1 ->
            modifies1 b h0 h1 /\
            as_seq h1 b == S.test  (as_seq h0 a) (v i) (as_seq h0 b))

let test a i b =
        b.(i) <- a.(i)

val test2:
    a:lbuffer uint64 3ul
    -> b:lbuffer uint64 3ul
    -> Stack unit
    (requires fun h -> live h a /\ live h b /\ disjoint a b)
    (ensures fun h0 r h1 ->
      modifies1 b h0 h1 /\
      as_seq h1 b ==S.test2 (as_seq h0 a) (as_seq h0 b))

let test2 a b =
    let spec h0 = S.test (as_seq h0 a)  in
    let h0 = ST.get() in
    loop1 (h0)(2ul) (b) (spec) (fun x -> Loop.unfold_repeati (2) (spec h0) (as_seq h0 b) (v x);
        test a x b)

val test3:
    a:lbuffer uint64 3ul
    -> b:lbuffer uint64 3ul
    -> c:lbuffer uint64 3ul
    -> Stack unit
        (requires fun h -> live h a /\ live h b /\ live h c /\ disjoint a b /\ disjoint a c /\ disjoint b c)
        (ensures fun h0 r h1 ->
            modifies2 b c h0 h1 /\
          as_seq h1 b ==S.test2 (as_seq h0 a) (as_seq h0 b) /\
          as_seq h1 c == S.test3 (as_seq h0 a) (as_seq h1 b) (as_seq h0 c))

let test3 a b c =
        push_frame();
        test2 a b;
        c.(0ul) <- b.(0ul);
        pop_frame()

**Comment by s-zanella** [comment]
Did you intend to write `S.test3 (as_seq h0 a) (as_seq h1 b) (as_seq h0 c))`? 
The implementation doesn't satisfy that, but substituting `h0` for `h1` in `as_seq h1 b` works.

**Comment by jamesbarne** [comment]
My bad, I swore I copied the correct file but I pasted an old one. Sorry about that. 

> Did you intend to write ```S.test3 (as_seq h0 a) (as_seq h1 b) (as_seq h0 c))```? 

No, this was an previous edition that I was fiddling with, and I changed to ```h0``` after realizing my mistake. 


Here are the correct files. It fails in ```F_impl.fst``` with the ```Could not prove post-condition``` for the ```test4``` function, which I suspect is due to ```test4``` technically modifies ```buffer b``` as well, and the ```unfold_repeati``` lemma does not account for that.   

```F_spec.fst```
```FStar
let test  (a:lseq uint64 3) (i:nat{i<3}) (b:lseq uint64 3): (lseq uint64 3) = 
    b.[i] <- a.[i]
	
let test2(a:lseq uint64 3)  (b:lseq uint64 3) : (lseq uint64 3) = 
    repeati 2 (test a) b

	
let test3 (a:lseq uint64 3)(b:lseq uint64 3)  (x:nat{x<3}) (c:lseq uint64 3) : (lseq uint64 3) = 
	let b = test2 a b in
	let c = c.[0] <- b.[0] in
	c
	
let test4 (a:lseq uint64 3) (b:lseq uint64 3) (c:lseq uint64 3): (lseq uint64 3) =
	repeati 2 (test3 a b) c 
```

```F_impl.fst```
```FStar
module F_impl

open FStar.HyperStack.All
open FStar.HyperStack
open FStar.HyperStack.ST
open Lib.IntTypes
open Lib.Buffer
module Loop = Lib.LoopCombinators
module ST = FStar.HyperStack.ST
module S = F_spec

val test:
    a:lbuffer uint64 3ul  
    -> i:size_t{v i < 3}
    -> b:lbuffer uint64 3ul  
    -> Stack unit
	(requires fun h -> live h a /\ live h b /\ disjoint a b)
	(ensures fun h0 r h1 -> 
	    modifies1 b h0 h1 /\
	    as_seq h1 b == S.test  (as_seq h0 a) (v i) (as_seq h0 b)) 
		
let test a i b =
	b.(i) <- a.(i)
	
val test2:
    a:lbuffer uint64 3ul
    -> b:lbuffer uint64 3ul 
    -> Stack unit
    (requires fun h -> live h a /\ live h b /\ disjoint a b)
    (ensures fun h0 r h1 -> 
        modifies1 b h0 h1 /\
        as_seq h1 b ==S.test2 (as_seq h0 a) (as_seq h0 b))

let test2 a b = 
    let spec h0 = S.test (as_seq h0 a)  in
    let h0 = ST.get() in
    loop1 (h0)(2ul) (b) (spec)
    (fun x -> 
        Loop.unfold_repeati (2) (spec h0) (as_seq h0 b) (v x);   
	test a x b)

val test3:
    a:lbuffer uint64 3ul  
    -> b:lbuffer uint64 3ul
    -> x:size_t{v x < 3}
    -> c:lbuffer uint64 3ul
    -> Stack unit
    (requires fun h -> live h a /\ live h b /\ live h c /\ disjoint a b /\ disjoint a c /\ disjoint b c)
    (ensures fun h0 r h1 -> 
        modifies2 b c h0 h1 /\
        as_seq h1 b ==S.test2 (as_seq h0 a) (as_seq h0 b) /\
	as_seq h1 c == S.test3 (as_seq h0 a) (as_seq h0 b) (v x) (as_seq h0 c))

let test3 a b x c = 
    push_frame();
    test2 a b;
    c.(0ul) <- b.(0ul);	
    pop_frame()
	
val test4:
    a:lbuffer uint64 3ul
    -> b:lbuffer uint64 3ul 
    -> c:lbuffer uint64 3ul
    -> Stack unit
    (requires fun h -> live h a /\ live h b /\ disjoint a b /\ live h c /\ disjoint a c /\ disjoint b c)
    (ensures fun h0 r h1 -> 
        modifies2 b c h0 h1 /\
        as_seq h1 b == S.test2 (as_seq h0 a) (as_seq h0 b) /\  //not sure if this is needed
        as_seq h1 c ==S.test4 (as_seq h0 a) (as_seq h0 b) (as_seq h0 c))
	 
let test4 a b c = 
    let spec h0 = S.test3 (as_seq h0 a) (as_seq h0 b)  in
    let h0 = ST.get() in
    loop1 (h0)(2ul) (c) (spec)
    (fun x -> Loop.unfold_repeati (2)(spec h0) (as_seq h0 c)(v x);   
    test3 a b x c)
```

**Comment by s-zanella** [comment]
@newuser1212 @jamesbarne Could you please post under a single identity?

`Lib.Buffer.loop1` only works when the body of the loop modifies a single buffer; `modifies1 ...` is part of the loop invariant. In your example `test3` is modifying 2 buffers, so you should use `Lib.Buffer.loop2` and change your specs accordingly.

Please make an effort to minimize examples in issues. This example could have been distilled to a single file and a couple of definitions.

**Comment by jamesbarne** [comment]
> @newuser1212 @jamesbarne Could you please post under a single identity?

Sorry about this we are logged into different accounts on separate computers and sometimes post separately.

**Comment by jamesbarne** [comment]
hi @s-zanella ,
Sorry I am still trying to figure out how to verify it. For the modifications in the specs, do I need to return something like a tuple instead as I am modifying two sequences?

**Comment by s-zanella** [comment]
Yes, the simplest is to work with pairs of byte sequences:
```FStar
let test (a:lseq uint64 3) (i:nat{i < 3}) (b:lseq uint64 3) : lseq uint64 3 =
  b.[i] <- a.[i]

let test2 (a:lseq uint64 3) (b:lseq uint64 3) : lseq uint64 3 =
  repeati 2 (test a) b

let test3 (a:lseq uint64 3) (i:nat{i < 3}) (bc:lseq uint64 3 & lseq uint64 3) : lseq uint64 3 & lseq uint64 3 =
  let b, c = bc in
  let b = test2 a b in
  let c = c.[0] <- b.[0] in
  b, c

let test4 (a:lseq uint64 3) (b:lseq uint64 3) (c:lseq uint64 3) : lseq uint64 3 & lseq uint64 3 =
  repeati 2 (test3 a) (b, c)
```

**Comment by s-zanella** [comment]
I assume my last comment answers the question. Feel free to reopen the issue if it does not.
