### ISSUE TITLE
Mismatch type in Lib.Sequence

### ISSUE THREAD

**Issue by Jazperson2** [project-everest/hacl-star#173]
In the ```Lib.Sequence``` module, the function ```index_generate_blocks``` in the ```fstar-master``` branch has a mismatch type. 

```FStar
Lib.Sequence.fst(255,8-255,29): (Error 19) Subtyping check failed; expected type j: Prims.nat{j < max}; got type Prims.int (see also prims.fst(441,17-441,23))
```

**Comment by s-zanella** [comment]
This subtyping check is done by Z3, so it's not guaranteed to succeed. I tried with the latest FStar master (3d9a371731476086701323a26106ad934337ec47, Z3 4.8.5) and it worked in interactive and batch mode. The hint for this query in the checked-in `.hints` file doesn't replay, but I could record a new hint that does replay.
