### ISSUE TITLE
Operations on Secret Integers

### ISSUE THREAD

**Issue by Jazperson2** [project-everest/hacl-star#187]
Is it not possible to perform a ```mod``` operation on two secret integers? 

For example:
```FStar
let mod_ab (a:uint8) (b:uint8{v b <> 0}) = mod #U8 a b
```
This fails to ``` Subtyping check failed; expected type Lib.IntTypes.int_t (Lib.IntTypes.U8) (Lib.IntTypes.PUB)```, which is obvious as uint8 is defined as a secure integer ```SEC```, while the ```mod``` operation is defined to only accept public integers ```PUB```.

Is there a reason for this? I see that it is the same for  ```div``` operation as well.

**Comment by beurdouche** [comment]
These operations are not constant-time on most platforms, so no they can’t be done on secrets. You can always shift (to divide by two) and add or multiply to get the result you want instead...

B.
