### ISSUE TITLE
EverCrypt_Hash_Incremental_free frees only partially

### ISSUE THREAD

**Issue by letmaik** [project-everest/hacl-star#189]
https://github.com/project-everest/hacl-star/blob/dd5ae444c560d736ff79c9d37a09cbb86504e231/providers/evercrypt/fst/EverCrypt.Hash.Incremental.fst#L788-L792

It frees the contents but not `s` itself. Therefore, currently one has to do something like that:
```c
EverCrypt_Hash_Incremental_state_s* s = EverCrypt_Hash_Incremental_create_in(a);
...
EverCrypt_Hash_Incremental_free(s);
free(s);
```

@protz

**Comment by s-zanella** [comment]
You're absolutely right. It was my oversight.
Pushed [a fix](https://github.com/project-everest/hacl-star/commit/73f2905ae32b3de817bad2466d36abc21ac640a9) and will merge it into `fstar-master` as soon as I get a CI green.

**Comment by s-zanella** [comment]
The fix is in `fstar-master` now
