### ISSUE TITLE
SIGILL due to lack of MOVBE support on i7-3770

### ISSUE THREAD

**Issue by jaybosamiya** [project-everest/hacl-star#191]
MOVBE is not supported on certain CPUs such as the i7-3770, and we should have a CPUID check for it.

We can check for MOVBE support using `CPUID.01H:ECX.MOVBE[bit 22]`. Shows up in `/proc/cpuinfo` as `movbe` under flags.

**Comment by R1kM** [comment]
This was fixed by PR #205
