### ISSUE TITLE
Unused variable in generated C code

### ISSUE THREAD

**Issue by franziskuskiefer** [project-everest/hacl-star#206]
`mul_felem5` [1] doesn't actually use `r50`, hence will produce unused variables in the resulting C code. For example in [Hacl_Poly1305_128.c](https://github.com/project-everest/hacl-star/blob/protz_git_c/dist/mozilla/Hacl_Poly1305_128.c#L146).

[1] https://github.com/project-everest/hacl-star/blob/fstar-master/code/poly1305/Hacl.Spec.Poly1305.Field32xN.fst#L296

**Comment by franziskuskiefer** [comment]
There's currently a hotfix in kremlin for this https://github.com/FStarLang/kremlin/commit/eeb6843cbfe6febb2c5c4c53b0bb2848280021ce in place. But this should probably be replaced at some point.

**Comment by msprotz** [comment]
This specific issue is gone, but I'm going to re-open a broader issue about unused variables in the generated C code.
