### ISSUE TITLE
Missing return statements in `EverCrypt_Hash_copy`

### ISSUE THREAD

**Issue by wintersteiger** [project-everest/hacl-star#218]
We get this:

```
KreMLin abort at ../../../external/evercrypt/dist/gcc-compatible/EverCrypt_Hash.c:772
unreachable (pattern matches are exhaustive in F*)
```

See [here](https://github.com/project-everest/hacl-star/blob/master/dist/gcc-compatible/EverCrypt_Hash.c#L676); `EverCrypt_Hash_copy` runs into the right branch (`scrut.tag == EverCrypt_Hash_SHA2_256_s` for us), but it doesn't return once it's done. 

@protz the F* code looks ok at first glance, so this may be a kremlin issue?

CC @letmaik @achamayou

**Comment by msprotz** [comment]
Thanks. Could you try refreshing the generated code without the `-fnoreturn-else` option?

**Comment by wintersteiger** [comment]
Yep, that fixes this particular problem, but I didn't check whether it introduces other problems elsewhere.

**Comment by protz** [comment]
This is only a recent addition. I'll disable it for now until I fix the bug.

Thanks for the report!

**Comment by wintersteiger** [comment]
Great, thanks!

**Comment by letmaik** [comment]
Should there be a test that exercises this case?

**Comment by msprotz** [comment]
I'm surprised that this didn't get caught because this: https://github.com/project-everest/hacl-star/blob/master/providers/test/Test.Hash.fst should under the hood call `copy`. Worth investigating.
