### ISSUE TITLE
P256 implementation bugs

### ISSUE THREAD

**Issue by franziskuskiefer** [project-everest/hacl-star#320]
The P256 implementation has a couple issues. It is in particular vulnerable to CVE_2017_10176 and a couple related issues.
See the [wycheproof tests](https://github.com/franziskuskiefer/evercrypt-rust/blob/master/evercrypt-rs/tests/test_p256.rs#L61) I had to disable because they were failing.

**Comment by Frosne** [comment]
I will take a look as soon as I'm back

**Comment by franziskuskiefer** [comment]
Turns out I didn't parse the test vectors in the right way for hacl to understand them properly.
I think takeaway from this is that P256 only handles inputs that are exactly the right length 🙂 
Fixed here https://github.com/franziskuskiefer/evercrypt-rust/commit/e6b7b31cdec1c080034e7d6cfb21efe8a460fa8a
