### ISSUE TITLE
ARM builds with clang are broken

### ISSUE THREAD

**Issue by franziskuskiefer** [project-everest/hacl-star#339]
`clang` doesn't like the constants in `Hacl_Impl_Blake2_Constants_rTable_S` (`error: argument to '__builtin_neon_vsriq_n_v' must be a constant integer`). The integers here really are constants, but `clang` doesn't understand this. So instead of using `Hacl_Impl_Blake2_Constants_rTable_S` something like

```
#define Hacl_Impl_Blake2_Constants_rTable_S_0 16
#define Hacl_Impl_Blake2_Constants_rTable_S_1 12
#define Hacl_Impl_Blake2_Constants_rTable_S_2 8
#define Hacl_Impl_Blake2_Constants_rTable_S_3 7
```

could be used.

https://github.com/project-everest/hacl-star/blob/51054f0b49464d49654792dbdeb08460262bd4c5/dist/gcc-compatible/Hacl_Blake2s_128.c#L168

**Comment by niekbouman** [comment]
Hi Franziskus,

I am not entirely sure, but this might be related to issue: https://github.com/project-everest/hacl-star/issues/337

**Comment by franziskuskiefer** [comment]
hm, I don't think so unfortunately. I tried the change from #337 and it didn't solve it. Also I think that the compiler just doesn't get that this array access is constant and that the array itself is constant.

**Comment by msprotz** [comment]
I thought we were testing compilation on ARM, see https://travis-ci.com/github/project-everest/hacl-star/jobs/373224002 for a successful build log. Could it be that this is a GCC/clang difference?

**Comment by msprotz** [comment]
@karthikbhargavan @polubelova didn't you already have a workaround for this? e.g. using `normalize_expr` or something for accesses to known constant indices of these global constant tables

**Comment by franziskuskiefer** [comment]
> I thought we were testing compilation on ARM, see https://travis-ci.com/github/project-everest/hacl-star/jobs/373224002 for a successful build log. Could it be that this is a GCC/clang difference?

Yes, it looks like GCC is ok with this but clang isn't ☹️

**Comment by polubelova** [comment]
Yeah, we could have the following fix:
```
  let r0 = normalize_term (Lib.Sequence.index (Spec.rTable al) 0) in
  normalize_term_spec (Lib.Sequence.index (Spec.rTable al) 0);
  let r1 = normalize_term (Lib.Sequence.index (Spec.rTable al) 1) in
  normalize_term_spec (Lib.Sequence.index (Spec.rTable al) 1);
  let r2 = normalize_term (Lib.Sequence.index (Spec.rTable al) 2) in
  normalize_term_spec (Lib.Sequence.index (Spec.rTable al) 2);
  let r3 = normalize_term (Lib.Sequence.index (Spec.rTable al) 3) in
  normalize_term_spec (Lib.Sequence.index (Spec.rTable al) 3);
```
it will be extracted as
```
    uint32_t r01 = (uint32_t)16U;
    uint32_t r11 = (uint32_t)12U;
    uint32_t r21 = (uint32_t)8U;
    uint32_t r31 = (uint32_t)7U;
```
I don't know why but `normalize_term` doesn't work with the stateful version of `rTable`.

**Comment by msprotz** [comment]
`normalize_term` cannot operate on stateful things because a stateful computation might generate a side-effect, which cannot be evaluated ahead of time -- so your suggestion is the right fix. thanks @polubelova !

@franziskuskiefer do you think you could try out that fix, possibly even adding a new travis target for arm/clang, to avoid such mishaps in the future?

**Comment by franziskuskiefer** [comment]
Looks like clang doesn't like this either ☹️ . I also tried the following (as `const` is what the compiler wants, see error message above). But not even that works.
Looking at the [docs](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics?search=vshlq_n_u32) the signature is `uint32x4_t vshlq_n_u32 (uint32x4_t a, const int n)` so this should work. I'm not really sure why ...

```
    const uint32_t r01 = (uint32_t)16U;
    const uint32_t r11 = (uint32_t)12U;
    const uint32_t r21 = (uint32_t)8U;
    const uint32_t r31 = (uint32_t)7U;
```

I'll have to look a little more at travis. The default clang on the ARM machines there is a little old (6) https://travis-ci.org/github/franziskuskiefer/hacl-star/jobs/719356012

**Comment by msprotz** [comment]
Can you try annotating `r0` to `r3` with `[@inline_let]`?

**Comment by franziskuskiefer** [comment]
I opened #340. Inlining works 👍
