### ISSUE TITLE
Broken submodule

### ISSUE THREAD

**Issue by franziskuskiefer** [project-everest/hacl-star#362]
https://github.com/project-everest/hacl-star/commit/05e0b0049aa4f6f2ca362ef44ff4548dbfda8f7b#diff-e111e895b719e3cbf8a5ac9cd36dba1b added a git submodule to `dist/test/c/kremlin`. But I don't see any `.gitmodule` file or other submodule definition. This breaks using `hacl-star` as a git submodule

```
git submodule update --init --recursive
fatal: No url found for submodule path 'hacl-star/dist/test/c/kremlin' in .gitmodules
```

**Comment by beurdouche** [comment]
Looks like this should be closed per https://github.com/project-everest/hacl-star/pull/363 ?
Please reopen if I am mistaken.
