### ISSUE TITLE
convert ed25519 pubkey to x25519

### ISSUE THREAD

**Issue by aep** [project-everest/hacl-star#388]
i'd like to implement this using hacl

https://github.com/jedisct1/libsodium/blob/ae4add868124a32d4e54da10f9cd99240aecc0aa/src/libsodium/crypto_sign/ed25519/ref10/keypair.c#L46-L67

but the first issue is that all the math are static symbols, secondly this doesnt seem to work:

```C++
pub fn conv_pub(u8 *i, u8 mut*out)
    where len(i)    >= 32
    where len(out)  >= 32
{
    u64 mut pk_field[20] = {0};
    point_decompress(pk_field, (u8 mut*)i);

    u64 mut one[10] = {1, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    u64 mut u_minus_one[10] = {0};
    Hacl_Impl_Curve25519_Field51_fsub(u_minus_one, pk_field, one);

    u64 mut u_plus_one[10] = {0};
    Hacl_Impl_Curve25519_Field51_fadd(u_plus_one, pk_field, one);

    FStar_UInt128_uint128 mut tmp[10] = {0};
    memset(tmp, 0, sizeof(tmp));
    u64 mut u_plus_one_inv[10] = {0};
    Hacl_Curve25519_51_finv(u_plus_one_inv, u_plus_one, tmp);

    memset(tmp, 0, sizeof(tmp));
    u64 mut pa_field[10] = {0};
    Hacl_Impl_Curve25519_Field51_fmul(pa_field, u_minus_one, u_plus_one_inv, tmp);

    store_51(out, pa_field);

    log::warn("CONVPUB");
    hex::fdump(stderr, i, 32);
    hex::fdump(stderr, out, 32);
    unsafe { hex::fdump(stderr, (u8*)pa_field, 32); }
}
```

any idea what i'm doing wrong there?
i believe the basic field ops work fine, since they work in reverse, but somehow i'm not loading the ed25519 pubkey correctly.
possibly something needs to be around point_decompress ?

**Comment by aep** [comment]
figured it out, the Z coordinate is actually stored at pk_field+10.  just need to have the rest of the functions use that.

keeping the question open, because it would be useful if this was either part of the standard api, or the api would expose the internal field functions.

**Comment by polubelova** [comment]
You can take a look at the following files which expose some internal finite field operations of curve25519_51.
- Low* code: https://github.com/project-everest/hacl-star/blob/master/code/ed25519/Hacl.EC.Ed25519.fst
- C code: https://github.com/project-everest/hacl-star/blob/master/dist/gcc-compatible/Hacl_EC_Ed25519.h

It seems to have all the functions needed to make your example work.

**Comment by aep** [comment]
thanks! i guess my fork is just outdated.
