### ISSUE TITLE
[$] Enable build system and optimize libintvector.h for Linux on Z (s390x)

### ISSUE THREAD

**Issue by edelsohn** [project-everest/hacl-star#403]
1. Update configuration and build system to allow EverCrypt to build on Linux on Z
2. Implement and optimize libintvector.h vector instruction abstraction for IBM z15 VX SIMD
3. Update EverCrypt to utilize vectorized implementation on Linux on Z
4. Update OCaml bindings for Linux on Z

**Comment by aj4ayushjain** [comment]
I am interested in implementing some parts of the project. Is it open to work or someone being assigned?

**Comment by edelsohn** [comment]
The project is nearly complete and is being implemented by the HACL* team.

**Comment by edelsohn** [comment]
I believe that this is completed with Pull #445 .  If the HACL* team agrees, this issue can be closed.

**Comment by aj4ayushjain** [comment]
Thanks for the update.
