### ISSUE TITLE
Make rules using $< without prerequisites

### ISSUE THREAD

**Issue by web-vertalo** [project-everest/hacl-star#423]
A number of rules in the top-level Makefile lack prerequisites yet use $< in the recipe:

```
%.fst:
          $(call run-with-log,\
            $(MONO) $(VALE_HOME)/bin/vale.exe -fstarText \
              -include $*.types.vaf \
              $(VALE_FLAGS) \
              -in $< -out $@ -outi $@i && touch -c $@i \
            ,[VALE] $(notdir $*),$(call to-obj-dir,$@))
```

```
obj/%.ml:
          $(call run-with-log,\
            $(FSTAR) $(notdir $(subst .checked,,$<)) --codegen $(CODEGEN) \
              --extract_module $(subst .fst.checked,,$(notdir $<)) \
            ,[EXTRACT-ML] $(notdir $*),$(call to-obj-dir,$@))
```

```
obj/%.krml:
          $(call run-with-log,\
            $(FSTAR) --codegen Kremlin \
              --extract_module $(basename $(notdir $(subst .checked,,$<))) \
              $(notdir $(subst .checked,,$<)) && \
            touch $@ \
            ,[EXTRACT-KRML] $*,$@)
```

What is the intended value for $< in these cases? The second of these looks like it should include prerequisite of obj/%.fst.checked, though that doesn't work for a target like Lib_Memzero0.ml. Without the prerequisite, I get an error for missing argument to --extract_module because $< is empty.

**Comment by msprotz** [comment]
Target dependencies are generated in the `.depend` then the pattern rules kick in to provide the recipe.

For the particular case of Lib_Memzero0.ml we recently cleaned up a hack, so now you may need to regenerate your .depend, and remove a few .ml in obj --  I suggest attempting to start from a clean build.

**Comment by web-vertalo** [comment]
A clean build from the latest master resolved this issue for me.
