### ISSUE TITLE
Running scons in vale/ looks for nonexistent ../specs/derived/Spec.Hash.Incremental.fst

### ISSUE THREAD

**Issue by web-vertalo** [project-everest/hacl-star#448]
How do I get past this?
```
scons: Reading SConscript files ...
FileNotFoundError: [Errno 2] No such file or directory: '../specs/derived/Spec.Hash.Incremental.fst':
  File "/usr/home/web/src/vertalo/everest/hacl-star/vale/SConstruct", line 1190:
    shutil.copy(source, target)
  File "/usr/local/lib/python3.7/shutil.py", line 248:
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.7/shutil.py", line 120:
    with open(src, 'rb') as fsrc:
```

**Comment by msprotz** [comment]
I don't think running `scons` in vale is supported anymore -- vale should be built as part of the global build of HACL*.

Thanks,

Jonathan

**Comment by web-vertalo** [comment]
I want to add support for the vale assembly  on FreeBSD. Can you point me to a pattern to follow for that work?

**Comment by msprotz** [comment]
are the FreeBSD calling conventions different from the ones on Linux/OSX? does the symbol naming scheme vary?

@Chris-Hawblitzel and @R1kM would know where to point you to -- I believe a starting point is  `vale/code/lib/util/CmdLineParser.ml` -- plus adding the relevant build productions in the main Makefile (just e.g. copy-pasting what is done for e.g. x86_64-darwing)

**Comment by R1kM** [comment]
As far as I understand from here: https://en.wikipedia.org/wiki/X86_calling_conventions#System_V_AMD64_ABI, calling conventions on FreeBSD should indeed be the same as on Linux/MacOS, for which we currently have vale assembly code.

@web-vertalo , I have no experience with FreeBSD, would existing linux assembly such as https://github.com/project-everest/hacl-star/blob/master/dist/gcc-compatible/poly1305-x86_64-linux.S be usable in your context?
Else, could you detail what changes would be needed to support FreeBSD? I'd be happy to point you to the changes needed in code.

**Comment by web-vertalo** [comment]
I'll look at whether the linux versions work as is on FreeBSD and report back the findings.
