### ISSUE TITLE
possible to use a single wasm file in the browser?

### ISSUE THREAD

**Issue by niekbouman** [project-everest/hacl-star#472]
Dear @protz and/or hacl-star devs,

I'm trying to use the WASM code in the browser. For my use case, I actually only need to verify Ed25519 signatures.

One question is if each WASM binary is 'self-contained', i.e., is it possible to only use "Hacl_Ed25519.wasm", or do I need the other wasm files as dependencies?

And, do you maybe have an example of how to use the WASM code from a web browser? (instead of via node.js) ? 

kind regards,
Niek

**Comment by denismerigoux** [comment]
Hi Niek,

I suggest you consult the `README.md` of the JS bindings directory: https://github.com/project-everest/hacl-star/tree/master/bindings/js. The Wasm binaries are not self-contained, you need to import `WasmSupport.wasm` and `LowStar_Endianness.wasm` for all or almost all of them, and then the dependencies follow the dependencies that primitives have on each other. You can look at https://signalstar.gforge.inria.fr/ for an example of the library in action.

**Comment by niekbouman** [comment]
hi Denis,

Thank you very much for your response/help.
I now have the following, as a rought test (by adapting `browser.js` in your example), 
the module containing the `Hacl_Ed25519_verify` function is found, but I cannot get the signature to verify correctly. (While it does work using Python's nacl signature verify funcs)

What also confuses me, is that in https://hacl-star.github.io/HaclSig.html#eddsa-verify it is claimed that the public key is 64 bytes, while it seems to me that this should be 32 bytes...

Do you maybe see what I am doing wrong?

best,
Niek

```js
//...
    .then(scope => {

      const msg = "hello\n";
      const pubkey = "4f4503e5d49daf1edc0d41c2951ce7208e909c432c07425d9e7d470d192af661";
      const sig = "f99f47bbd6d8dfd14b131e1ca26a20520f4f9e736fcb4156da7ed61609a81e788439ff5e65ea983dc940edb140a717504621a62e585323cdf0f7a75a99cdd00d";

      console.log(fromHexString(pubkey));
      console.log(enc.encode(msg));
      console.log(fromHexString(sig));

      var enc = new TextEncoder();
      const fromHexString = hexString => new Uint8Array(hexString.match(/.{1,2}/g).map(byte => parseInt(byte, 16)));

      let x = scope['Hacl_Ed25519'].Hacl_Ed25519_verify(fromHexString(pubkey),6, enc.encode(msg) , fromHexString(sig));

      for (let m of Object.keys(scope)) {
        if ("Hacl_Ed25519_verify" in scope[m]) {
          my_print("... verify found in module " + m +"   "+  (x ? "true" : "false"));
          return ; //..scope[m].main(scope);
        }
      }

```

**Comment by denismerigoux** [comment]
The F* signature of Hacl's Ed25519 verify functions does indeed say it's a 32-bytes public key:

https://github.com/project-everest/hacl-star/blob/2e797ff3c0a032cdf113f1745703d8e533ce967b/code/ed25519/Hacl.Ed25519.fsti#L19-L28

@protz should the doc be changed ?

The exported wasm function has been tested under CI with these values: 

https://github.com/project-everest/hacl-star/blob/2e797ff3c0a032cdf113f1745703d8e533ce967b/bindings/js/api.json#L349-L406

I don't know why your code does not work. Maybe it has something to do with the `\n` in the message that gets encoded as binary differently in Javascript and in Python ?

**Comment by niekbouman** [comment]
Hi Denis,

I think I now understand my mistake; I used your libsignal protocol example, which does not use api.js.
I now see that in order to call the raw wasm function by hand (without api.js) , there is a special calling convention to follow for providing the arguments, which I completely omitted :-).

The problem is that I cannot use api.js directly in a browser (non-nodejs) setting. Do you have advice on how to "browserify" it? (There is a project on the web with that name, but I doubt that it supports use cases involving wasm).

In you ci-tests I see hex-strings. Another question I have is where the hex-encoding/decoding steps are performed? Is that happening inside the WASM module or in the js wrapper?

**Comment by denismerigoux** [comment]
Yep you can use `browserify` to replace the node includes. To handle wasm modules you just have to change the way to fetch the raw binary file of the module (switching node filesystem api to a network fetch).

The hex-encoding/decoding is done in the JS wrapper.

**Comment by niekbouman** [comment]
Merci beaucoup!!

**Comment by beurdouche** [comment]
@denismerigoux can you triage this please (keep open, close, and set the appropriate labels)? Thanks a lot !
