### ISSUE TITLE
Split Hacl_Hash

### ISSUE THREAD

**Issue by franziskuskiefer** [project-everest/hacl-star#476]
The `Hacl_Hash.c` bundles blake2 and sha2 together, which results in everything using sha2 to include blake2 as well. For example building ed25519 requires to include blake2.

**Comment by msprotz** [comment]
How about:
```
Hacl_Hash_SHA2
Hacl_Hash_Legacy
Hacl_Hash_Blake2
```
? Would that be good?

**Comment by franziskuskiefer** [comment]
Sounds good. I don't know if anyone really cares about MD5 and SHA1. (Given that there are `Hacl_Streaming_SHA1.c` and `Hacl_Streaming_MD5.c` it would be consistent to also have `Hacl_Hash_SHA1.c` `Hacl_Hash_MD5.c` though.)
