### ISSUE TITLE
Correct way to use Evercrypt API from multiple cpu cores (threads)?

### ISSUE THREAD

**Issue by niekbouman** [project-everest/hacl-star#478]
Dear hacl-star/evercrypt team,

I'd like to use/call Evercrypt's CTR api from multiple CPU cores, in a thread-per-core design.
What would be the correct way to perform the auto-initialization for the agile APIs in this scenario?

Is it correct to call `EverCrypt_AutoConfig2_init();` only from a single core (say core 0), and after that, each core can call into the agile APIs?

And are there any multi-threading caveats to be aware of ?

kind regards,
Niek

**Comment by msprotz** [comment]
Hi Niek,

These are global variables under the hood, so I assume in your model they would be shared by all threads in the process? In that case, I would call the `init` function first, then create the threads and dispatch them to the right cores

**Comment by niekbouman** [comment]
I'll do that, then. Thanks Jonathan!
