### ISSUE TITLE
How to understand some word, such as "noeq"?

### ISSUE THREAD

**Issue by WestSuper** [project-everest/hacl-star#504]
I have a question for understand the code,  could you tell me how to understand some word, such as "noeq"?

**Comment by msprotz** [comment]
`noeq type t` means that two elements of the type `t` cannot be compared via the polymorphic equality operator `=`

**Comment by WestSuper** [comment]
Thank you very much. Is there some terminology library or link for those words, I also not understand "unfold", "inline_for_extraction", "noextract" and so on. Meanwhile, I also don't know how to understand  #set-options "--max_fuel 0 --max_ifuel 0 --z3rlimit 50" , are there any details?

**Comment by WestSuper** [comment]
https://github.com/FStarLang/FStar/wiki
