### ISSUE TITLE
Could not find AES test file

### ISSUE THREAD

**Issue by 15646739752** [project-everest/hacl-star#509]
I was debugging the Hacl_AES project , I configured a series of .h files as prompted in these file on Github, but I never found the test file. Then I tried to write the main function for testing, and found that the encryption and decryption results were not correct, so I would like to ask where our test file is. I did not find the test file about AES in test.

**Comment by beurdouche** [comment]
Hmm... I am surprised that AES is even in dist/ directory of the main branch. It should definitely not.
At the moment, it is not verified code but just some experiment, so I would not be surprised if it is buggy.

@karthikbhargavan @protz Likely an Evercrypt related issue?
This should be minimally moved to an experimental subdirectory in dist, if not removed entirely.
@polubelova @Frosne Any opinion on this?

**Comment by msprotz** [comment]
I don't know why this is here. This is the unverified experimental version. I think miTLS might have needed it at some point but I'm in favor of removing it.

**Comment by 15646739752** [comment]
Is the C program of AES the F * program of AES converted by the KreMLin tool?

**Comment by beurdouche** [comment]
Yes, but the F* code has no proofs in this case.

**Comment by 15646739752** [comment]
I'm sorry, when you say not proven do you mean not formally verified or do you mean not verified to be correct?

**Comment by msprotz** [comment]
The code is a prototype from several years ago that acts as a placeholder until we have a fully verified implementation of AES. Specifically, we don't have a theorem that says that this code is memory-safe, or functionally correct vis à vis a reference specification.

I hope this helps. In the meanwhile, I'm closing this issue, as this file should never have been around in the first place.
