### ISSUE TITLE
About the Evercrypt. AEAD file

### ISSUE THREAD

**Issue by 15646739752** [project-everest/hacl-star#513]
Hi，
   Were the AES-GCM and other C programs related to AES in the Evercrypt. AEAD file converted from the Kremlin? And is it formally verified？

**Comment by msprotz** [comment]
EverCrypt.AEAD is formally verified and implements:
- AES-GCM in assembly via the Vale technology, provided your computer has the AESNI instruction
- ChachaPoly in regular C
- ChachaPoly with intrinsics for ARM NEON, AVX128, AVX256

Hope this helps. hacl-star.github.io/ may have more relevant info.
