### ISSUE TITLE
Remove all unused definitions from the extracted header files

### ISSUE THREAD

**Issue by beurdouche** [project-everest/hacl-star#63]
Everything that is annotated with `private` in the F* code, should probably not be extracted to the header files. This has to be discussed with @msprotz

**Comment by msprotz** [comment]
https://github.com/FStarLang/kremlin/blob/master/MANUAL.md#generating-static-functions describes why this is not always possible -- if you have a specific, minimal repro, I'm happy to take a look at it

please also note that unused functions are plainly eliminated if:
- you have a `main` function to act as the root of the reachability analysis, or
- you are using `-bundle API=...` where API is a module that tells you which functions are public (which entails that anything not reachable through the API can be dropped)

**Comment by beurdouche** [comment]
I was actually thinking mainly of type declarations. I don't think those are handled at all, are they ?

**Comment by msprotz** [comment]
Ah, good point, yes. Can you file an issue at https://github.com/FStarLang/kremlin/issues?

**Comment by msprotz** [comment]
It's been on my plate for a while but there's no specific kremlin issue for it.

**Comment by beurdouche** [comment]
Depends on https://github.com/FStarLang/kremlin/issues/63
This is high priority as it is a requirement to push more code into production

**Comment by beurdouche** [comment]
Fixed by Kremlin
