### ISSUE TITLE
Clean up secure_api/Makefile

### ISSUE THREAD

**Issue by sishtiaq** [project-everest/hacl-star#7]
`secure_api/Makefile` concatenates `low-level/Makefile` and ``low-level/crypto/Makefile`, refactoring much needed.
- One lost feature is having a Makefile in each directory, so that emacs can call “make …fst-in”. Started in `aead`.
- General question: how do we know we are verifying enough? Unclear now that we verify one file at a time.
- Practical goal: “make extra” succeeds with no hints. Right now we have some regressions (and larger rlimits); Instabilities in proofs should at least be commented in the code (see UF1CMA alloc, AEAD.Encoding, and current status on slack).
- We need Makefile entries to document and automate performance measurements, e.g. to check changes do not degrade perfs.

**Comment by beurdouche** [comment]
@fournet @s-zanella @ad-l @karthikbhargavan 
When restoring CI, I had to remove `vale` that was failing and was the only thing under testing. 
Can one of you take the lead on this and make sure that `secure_api` is building properly, verifying and tested in the master branch. Having stale code in master doesn't make sense, if it is working somewhere in a branch... :)

**Comment by msprotz** [comment]
There is an extensive new Makefile in secure_api on the `fstar-master` branch; perhaps we could use that, and make sure it performs verification, instead of lax verification?

**Comment by beurdouche** [comment]
This is supposedly resolved in `fstar-master`
